# docker-compose.yml
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    environment:
      - NODE_ENV=production  # Set environment variable for production mode
    volumes:
      - .:/app  # Sync files between the host and container for development
      # Exclude node_modules and .next to avoid overwriting the build in the container
      - /app/node_modules
      - /app/.next
